"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$line_break$character"""

palette = 'vague_black'

[palettes.vague_black]
bg_dark = "#141415"      # Main background (darkest)
bg_medium = "#252530"    # Secondary background
bg_light = "#606079"     # Tertiary background (lighter shade)
fg_primary = "#cdcdcd"   # Primary text
fg_secondary = "#d7d7d7" # Brighter text
fg_dim = "#878787"       # Dimmed text
red = "#d8647e"
red_bright = "#e08398"
green = "#7fa563"
green_bright = "#99b782"
yellow = "#f3be7c"
yellow_bright = "#f5cb96"
blue = "#6e94b2"
blue_bright = "#8ba9c1"
magenta = "#bb9dbd"
magenta_bright = "#c9b1ca"
cyan = "#aeaed1"
cyan_bright = "#bebeda"

[os]
disabled = true

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:bg_light fg:bg_dark"
style_root = "bg:bg_medium fg:red_bright"
format = '[ $user ]($style)'

[directory]
style = "fg:fg_primary bg:bg_medium"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:bg_dark bg:blue)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:bg_dark bg:blue)]($style)'

[nodejs]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:bg_dark bg:green)]($style)'

[c]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:bg_dark bg:green)]($style)'

[rust]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:bg_dark bg:green)]($style)'

[golang]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:bg_dark bg:green)]($style)'

[php]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:bg_dark bg:green)]($style)'

[java]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:bg_dark bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:bg_dark bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:bg_dark bg:green)]($style)'

[python]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:bg_dark bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:magenta"
format = '[[ $symbol( $context) ](fg:bg_dark bg:cyan)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:magenta)'
vimcmd_replace_symbol = '[](bold fg:magenta)'
vimcmd_visual_symbol = '[](bold fg:cyan_bright)'
