return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.test.neotest" },
  { import = "astrocommunity.scrolling.mini-animate" },
  { import = "astrocommunity.comment.mini-comment" },
  { import = "astrocommunity.debugging.telescope-dap-nvim" },
  { import = "astrocommunity.icon.mini-icons" },
  { import = "astrocommunity.git.mini-git" },
  { import = "astrocommunity.markdown-and-latex.markdown-preview-nvim" },
  { import = "astrocommunity.pack.go" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.search.nvim-spectre" },
  { import = "astrocommunity.pack.yaml" },
  { import = "astrocommunity.pack.toml" },
  { import = "astrocommunity.pack.bash" },
  { import = "astrocommunity.pack.typescript" },
  { import = "astrocommunity.pack.tailwindcss" },
  { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.pack.mdx" },
}
