#!/usr/bin/env python3

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CODEX_ROOT = ROOT / "codex" / ".codex"
CLAUDE_ROOT = ROOT / "claude" / ".claude"
COMMANDS_ROOT = CLAUDE_ROOT / "commands"
AGENT_SOURCES = [
    CLAUDE_ROOT / "commands" / "agent" / "agent-browser-automation.md",
    CLAUDE_ROOT / "commands" / "agent" / "merge" / "agent-prep-merge.md",
    *sorted((CLAUDE_ROOT / "commands" / "agent" / "persona").glob("*.md")),
]
AGENT_BLOCK_START = "# SuperClaude agents — generated by port_superclaude.py"
AGENT_BLOCK_END = "# End SuperClaude agents"


def strip_frontmatter(text: str) -> str:
    if text.startswith("---\n"):
        _, _, rest = text.split("---\n", 2)
        return rest.lstrip()
    return text


def parse_frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---\n"):
        return {}
    frontmatter, _, _ = text.split("---\n", 2)
    # Unreachable for valid frontmatter; keep fallback simple.
    if not frontmatter:
        parts = text.split("---\n", 2)
        if len(parts) < 3:
            return {}
        frontmatter = parts[1]
    meta: dict[str, str] = {}
    raw = text.split("---\n", 2)[1]
    for line in raw.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip().strip('"').strip("'")
    return meta


def normalize_command_body(text: str) -> str:
    text = strip_frontmatter(text)
    replacements = {
        "/sc:": "$sc-",
        "/sc ": "$sc ",
        "`/sc`": "`$sc`",
        "TodoWrite": "update_plan",
        "Task": "spawn_agent",
        ".claude/": ".codex/",
        "Claude Code": "Codex",
        "$ARGUMENTS": "{{SC_ARGS}}",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    lines = []
    for line in text.splitlines():
        if "!`" in line:
            continue
        lines.append(line)
    text = "\n".join(lines)
    return text.strip() + "\n"


def normalize_agent_body(text: str, title: str) -> str:
    text = strip_frontmatter(text)
    text = text.replace("$ARGUMENTS", "the user request")
    text = text.replace("Claude Code", "Codex")
    text = text.replace("Task", "spawn_agent")
    context_block = re.compile(r"## Context\s+.*?## Your task", re.DOTALL)
    if context_block.search(text):
        text = context_block.sub(
            "## Context\n"
            "You are a SuperClaude specialist agent adapted for Codex collaboration.\n\n"
            "## Your task",
            text,
        )
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("- Session ID: !`"):
            continue
        if stripped.startswith("- Current directory: !`"):
            continue
        if stripped.startswith("- Project structure: !`"):
            continue
        if stripped.startswith("- Package files: !`"):
            continue
        if stripped.startswith("- Framework detection: !`"):
            continue
        lines.append(line)
    cleaned = "\n".join(lines).strip()
    preamble = (
        f"# {title}\n\n"
        "Ported from the SuperClaude framework for Codex multi-agent use.\n\n"
    )
    return preamble + cleaned + "\n"


def skill_name_for(path: Path) -> str:
    rel = path.relative_to(COMMANDS_ROOT).with_suffix("")
    parts = list(rel.parts)
    if parts == ["sc", "sc"]:
        return "sc"
    if parts and parts[0] == "sc":
        return "sc-" + "-".join(parts[1:])
    return "-".join(parts)


def agent_name_for(path: Path) -> str:
    stem = path.stem
    for prefix in ("agent-persona-", "agent-"):
        if stem.startswith(prefix):
            stem = stem[len(prefix) :]
            break
    return f"sc-{stem}"


def title_from_slug(slug: str) -> str:
    return slug.replace("-", " ").title()


def write_skill(path: Path) -> None:
    name = skill_name_for(path)
    raw = path.read_text()
    meta = parse_frontmatter(raw)
    body = normalize_command_body(raw)
    outdir = CODEX_ROOT / "skills" / name
    if name.startswith("gsd-") and outdir.exists():
        return
    outdir.mkdir(parents=True, exist_ok=True)
    rel = path.relative_to(COMMANDS_ROOT).with_suffix("")
    original_name = meta.get("name", ":".join(rel.parts))
    description = meta.get("description", f"Codex port of {original_name}")
    skill = f"""---
name: "{name}"
description: "{description}"
metadata:
  short-description: "Claude command port"
---

<codex_skill_adapter>
## A. Skill Invocation
- This skill is invoked by mentioning `${name}`.
- Treat all user text after `${name}` as `{{{{SC_ARGS}}}}`.
- If no arguments are present, treat `{{{{SC_ARGS}}}}` as empty.

## B. Claude Command Translation
- This skill is a Codex-native port of the Claude command tree and SuperClaude framework.
- Translate Claude `spawn_agent(...)` patterns to Codex `spawn_agent(...)`.
- Translate Claude planning/checklist language to Codex `update_plan`.
- Prefer existing Codex MCP servers from `config.toml` when the original command mentions MCP.

## C. Compatibility Notes
- Original command: `{original_name}`.
- Codex invocation: `${name}`.
- Preserve the behavioral intent of the source command, but use Codex-native tools and collaboration primitives.
</codex_skill_adapter>

{body}"""
    (outdir / "SKILL.md").write_text(skill)


def write_agent(path: Path) -> None:
    name = agent_name_for(path)
    title = title_from_slug(name.removeprefix("sc-"))
    md_path = CODEX_ROOT / "agents" / f"{name}.md"
    toml_path = CODEX_ROOT / "agents" / f"{name}.toml"
    md_path.write_text(normalize_agent_body(path.read_text(), title))
    toml_path.write_text(
        'sandbox_mode = "workspace-write"\n'
        f'developer_instructions_file = "agents/{name}.md"\n'
    )


def update_config(agent_sources: list[Path]) -> None:
    config_path = CODEX_ROOT / "config.toml"
    config = config_path.read_text().rstrip() + "\n"
    entries: list[str] = []
    for path in agent_sources:
        raw = path.read_text()
        meta = parse_frontmatter(raw)
        name = agent_name_for(path)
        description = meta.get("description", f"SuperClaude port for {name}")
        entries.append(
            f'[agents.{name}]\n'
            f'description = "{description}"\n'
            f'config_file = "agents/{name}.toml"\n'
        )
    block = (
        f"{AGENT_BLOCK_START}\n\n"
        + "\n".join(entries).rstrip()
        + f"\n\n{AGENT_BLOCK_END}\n"
    )
    pattern = re.compile(
        rf"\n{re.escape(AGENT_BLOCK_START)}.*?{re.escape(AGENT_BLOCK_END)}\n?",
        re.DOTALL,
    )
    if pattern.search(config):
        config = pattern.sub("\n" + block, config)
    else:
        config = config.rstrip() + "\n\n" + block
    config_path.write_text(config)


def main() -> None:
    for path in sorted(COMMANDS_ROOT.rglob("*.md")):
        if path.name == "README.md":
            continue
        write_skill(path)
    for path in AGENT_SOURCES:
        write_agent(path)
    update_config(AGENT_SOURCES)
    print("SuperClaude port complete.")


if __name__ == "__main__":
    main()
